name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    
    - name: 'Run checkout'
      uses: actions/checkout@v2

    - name: 'Run login az'
      run : |
        az account set --subscription 7b2c8510-cb1a-4eff-b866-29eb206b33b0
        az aks get-credentials --resource-group Exo1_group --name Exo1 --overwrite-existing
        
        case ${{ github.actor }} in 
          "SunnyBenji") 
            kubectl config set-context --current --namespace=workspace-bjb-2000
            ;;
          "Terminev") 
            kubectl config set-context --current --namespace=workspace-alc-2000
            ;;
          "AlexGuillemin91") 
            kubectl config set-context --current --namespace=workspace-ag-1998
            ;;
          "MBoutray") 
            kubectl config set-context --current --namespace=workspace-mdb-1997
            ;;
          *)
            echo "No matching namespace found for user: $github_actor"
            ;;
        esac

    - name: 'Run Azure CLI commands'
      run: |
        docker build -t devbaam.azurecr.io/alex-hello-world-app .
        az acr login --name devbaam 
        docker push devbaam.azurecr.io/alex-hello-world-app
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml